title: Writer Collective
email: atxwritercollective@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  writers of fiction podcasts, YA stories, and contemporary fiction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://writerscollective.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  writerscollective

# Settings
paginate: 5
sass:
  sass_dir: _sass
  style: compressed
markdown: kramdown
srcset:
  cache: "/images/resize"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-srcset
  - github-pages
